### ISSUE TITLE
Leaves view

### ISSUE THREAD

**Issue by chanthoeurntuon20** [pnc-virtual-company/2020-G7-LMS#11]
When the manager HR and Admin view leave request of employee they can see fields :
- Employee name 
- Start date
- End date
-Duration
-Type of leave
- Accept
- Reject
They can accept and reject the leave request employee.

**Comment by soklyphornweb2020** [comment]
@radytrainer  Good evening teacher, I'm already complete leave view, Please check it.

**Comment by soklyphornweb2020** [comment]
@radytrainer Good morning teacher,I'm complete leaves summit already.So please check it thank you.

**Comment by soklyphornweb2020** [comment]
@radytrainer Good morning teacher, I'm complete leave submit already please, check it again teacher.

**Comment by soklyphornweb2020** [comment]
@radytrainer  Good evening teacher, I'm complete leave submit already, please check it again teacher.
