### ISSUE TITLE
Login:Controllers/Models

### ISSUE THREAD

**Issue by chanthoeurntuon20** [pnc-virtual-company/2020-G7-LMS#13]
User need login with email and password:
- user can click the button next if they correct information on the input field
- The message error will show if they not correct information

**Comment by senghorkhen** [comment]
@radytrainer Good afternoon teacher I would like you to check my task about process login and logout. Please check it. Thanks

**Comment by senghorkhen** [comment]
@radytrainer Good morning teacher I would you to check my task about login and logout. Please check it.
