### ISSUE TITLE
Design database table

### ISSUE THREAD

**Issue by chanthoeurntuon20** [pnc-virtual-company/2020-G7-LMS#3]
In this application, there are 5 tables:
-Employee
-Department
-Leave request
-Position
-Role

**Comment by chanthoeurntuon20** [comment]
@radytrainer good afternoon teacher, now my team already completed the design database table. Please check it.

**Comment by chanthoeurntuon20** [comment]
@radytrainer  hello teacher, We already update please check it again.

**Comment by radytrainer** [comment]
thanks
