### ISSUE TITLE
Employee view

### ISSUE THREAD

**Issue by chanthoeurntuon20** [pnc-virtual-company/2020-G7-LMS#8]
A view composed of
-Text field for the first name
-Text field for the last name
-Text field for Department
-Text field for Position
-Text field for the start date
- Create button
- Discard button

**Comment by nisayourm** [comment]
@radytrainer Good morning teacher I hope you are doing well. I would like to invite you to check my task work.

**Comment by chanthoeurntuon20** [comment]
@Helenmartinot Good evening Helen, I hope you are doing well. I have some questions to ask you about form create employees. When we create employees you want us to put the start date field or not?

**Comment by Helenmartinot** [comment]
Dear, 
I am doing great thank you. Hope you are too. Yes, I would like to see for each employee when they started working for us. This way, it helps us to calculate how many leave days they are allowed to have. 
Have a good day, 
Helen Martinot

**Comment by chanthoeurntuon20** [comment]
Yes thank you I will do on it.
